name: Cypress Tests
on: push
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   strategy:
    # don't fail the entire matrix on failure
    fail-fast: false
    matrix:
      # run copies of the current job in parallel
      specs: ['./cypress/e2e/speccFileSequence.cy.js']
      cointainers: [1, 2, 3, 4, 5]
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
          record: true
          parallel: true
          group: 'UI-Chrome'
          start: npm start
          command: npm run RunAllTest
          browser: chrome 
